export default {
  root: '/input',
  cacheDir: '/tmp/vite-cache',
  configFile: false,
  css: { postcss: { plugins: [] } },
  esbuild: { tsconfigRaw: {} },
  resolve: { alias: { vitest: '/build/apps/validation-executor/node_modules/vitest' } },
  test: {
    include: ['**/*.test.{ts,js}'],
    exclude: [],
    environment: 'node',
    watch: false,
    coverage: { enabled: false },
    pool: 'forks',
    poolOptions: { forks: { singleFork: true } },
    fileParallelism: false,
    testTimeout: 5000,
    hookTimeout: 5000,
    reporters: ['json'],
    outputFile: '/output/report.json',
    cache: false,
    passWithNoTests: false,
    dangerouslyIgnoreUnhandledErrors: false,
  },
};
