import { createHash } from 'node:crypto';
import type { AiSource, AiMlSource } from '../src/collaboration/validation-ai-content';
export const hash = (s: string) => createHash('sha256').update(s).digest('hex');
export function aiFixture() {
  const digest = hash('proposal'),
    headSha = 'a'.repeat(40),
    baseSha = 'b'.repeat(40),
    snapshotDigest = hash('original'),
    candidateDigest = hash('patched');
  const file = {
    id: 'file',
    path: 'src/auth.ts',
    operation: 'MODIFY',
    oldBlobSha: 'c'.repeat(40),
    oldContentHash: hash('old'),
    newContentHash: hash('new'),
    diff: '--- a/src/auth.ts\n+++ b/src/auth.ts\n@@ -1 +1 @@\n-return eval(input);\n+return input;\n',
  };
  const proposal = {
    id: 'proposal',
    organizationId: 'org',
    repositoryId: 'repo',
    pullRequestId: 'pr',
    conversationId: 'conversation',
    turnId: 'turn',
    status: 'ACCEPTED',
    revision: 1,
    digest,
    headSha,
    baseSha,
    files: [file],
  };
  const app = {
    id: 'app',
    organizationId: 'org',
    repositoryId: 'repo',
    pullRequestId: 'pr',
    turnId: 'turn',
    status: 'APPLIED',
    cleanup: 'DISPOSED',
    proposalId: 'proposal',
    proposalRevision: 1,
    proposalDigest: digest,
    baseSha,
    headSha,
    proposal,
    attempts: [
      {
        status: 'APPLIED',
        cleanup: 'DISPOSED',
        snapshotDigest,
        manifestDigest: candidateDigest,
        files: [{ path: file.path, contentHash: file.newContentHash }],
      },
    ],
  };
  const staticAnalyses = ['ORIGINAL', 'PATCHED'].map((side) => ({
    id: 'static-' + side,
    validationId: 'validation',
    organizationId: 'org',
    side,
    status: 'COMPLETE',
    reason: null,
    rulesetVersion: 'v1',
    rulesetDigest: hash('rules'),
    configurationDigest: hash('config'),
    sourceDigest: side === 'ORIGINAL' ? snapshotDigest : candidateDigest,
    resultDigest: hash(side),
    findingCount: side === 'ORIGINAL' ? 1 : 0,
    findings:
      side === 'ORIGINAL'
        ? [
            {
              id: 'finding',
              analysisId: 'static-ORIGINAL',
              organizationId: 'org',
              analyzer: 'PATTERN',
              ruleId: 'eval',
              severity: 'HIGH',
              category: 'SECURITY',
              path: file.path,
              startLine: 1,
              endLine: 1,
              message: 'Dynamic evaluation no longer detected in candidate.',
              classification: 'RESOLVED',
              comparability: 'MATCHED',
              findingDigest: hash('finding'),
              counterpartDigest: null,
            },
          ]
        : [],
  }));
  const run = {
    id: 'validation',
    organizationId: 'org',
    repositoryId: 'repo',
    pullRequestId: 'pr',
    turnId: 'turn',
    conversationId: 'conversation',
    applicationId: 'app',
    proposalId: 'proposal',
    proposalRevision: 1,
    proposalDigest: digest,
    headSha,
    snapshotDigest,
    candidateDigest,
    state: 'COMPLETED',
    cleanup: 'DISPOSED',
    profiles: ['typescript-typecheck-v1'],
    application: app,
    staticAnalyses,
    attempts: [
      {
        steps: ['ORIGINAL', 'PATCHED'].map((side) => ({
          id: 'step-' + side,
          validationId: 'validation',
          organizationId: 'org',
          side,
          profile: 'typescript-typecheck-v1',
          outcome: 'PASS',
          inputDigest: hash('input-' + side),
          resultDigest: hash('result-' + side),
          observed: {
            started: true,
            termination: 'EXITED',
            exitCode: 0,
            oom: false,
            cleanup: 'DISPOSED',
          },
          runnerReported: { status: 'VALID', report: { kind: 'typecheck', total: 1, failed: 0 } },
        })),
      },
    ],
  } as unknown as AiSource;
  const ml = {
    id: '00000000-0000-4000-8000-000000000001',
    organizationId: 'org',
    repositoryId: 'repo',
    pullRequestId: 'pr',
    validationId: run.id,
    applicationId: app.id,
    proposalId: proposal.id,
    proposalRevision: 1,
    proposalDigest: digest,
    baseSha,
    headSha,
    snapshotDigest,
    candidateDigest,
    state: 'COMPLETED',
    outcome: 'LOWER',
    deltaTenths: -78,
    bandMovement: 'UNCHANGED',
    resultDigest: hash('ml'),
    frozenMetadataDigest: hash('meta'),
    featureSchemaVersion: 'v1',
    extractorVersion: 'v1',
    modelIdentity: { modelName: 'bootstrap', artifactDigest: hash('artifact') },
    assessments: ['ORIGINAL', 'PATCHED'].map((side) => ({
      organizationId: 'org',
      side,
      availability: 'AVAILABLE',
      scoreTenths: side === 'ORIGINAL' ? 835 : 757,
      band: 'HIGH',
      warnings: ['Synthetic target, not vulnerability probability'],
      staticResultDigest: hash(side),
    })),
  } as unknown as AiMlSource;
  return { run, ml };
}
